# Application Name
spring:
  application:
    name: JWTTokenValidation




#  security:
#    user:
#      name: Sathiya
#      password: Seelan@123

  # db connection details
  datasource:
    url: jdbc:mysql://localhost:3306/spring_validations?createDatabaseIfNotExist=true
    username: root
    password: Sathiya@1987

  # it will show the sql as visible in the port
  # Everytime the table will create when the application starts..
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update


    # ----------------------- connection to use H2 db -------------------------:
    # spring:
    #  datasource:
    #   url: jdbc:h2:mem:users
    #    username: sa
    #  h2:
    #    console:
    #      enable: true
    #      settings:
    #        web-allow-others: true







#  spring.main.allow-circular-references=true
#  spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#  spring.datasource.url = jdbc:mysql://localhost:3306/university
#  spring.datasource.username = root
#  spring.datasource.password = 143@Arpilu
#  spring.jpa.hibernate.ddl-auto = update
#  spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
#  spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl